# language: node_js
# node_js:
#   - "8.2"
#  before_install:
#     - export CHROME_BIN=/usr/bin/google-chrome
#     - export DISPLAY=:99.0
#     - sh -e /etc/init.d/xvfb start
#     - sudo apt-get update
#     - sudo apt-get install -y libappindicator1 fonts-liberation
#     - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#     - sudo dpkg -i google-chrome*.deb
#   addons:
#   chrome: stable

sudo: required
dist: trusty
language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # - npm i -g npm@5
# install:
#   - npm install
script:
  - node test/e2e/runner.js
